name: Web Monitor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # för att kunna pusha med egen token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python main.py

      - name: Commit changes to cache files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_products.json available_products.json || echo "Inga filer att lägga till"
          git diff --quiet && echo "Inga ändringar att committa" || git commit -m "Uppdaterar cache-filer från workflow"
          git push origin main
        env:
          # Kräver repo-token med push-rättigheter
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
