name: Web Monitor

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:       # Möjliggör manuell körning från GitHub UI

permissions:
  contents: write          # Viktigt för att kunna pusha filer

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure data folder and files exist
        run: |
          mkdir -p data
          # Skapar tomma filer om de inte finns för att undvika fel i scriptet
          touch data/seen_products.json
          touch data/available_products.json

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run monitor script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit and push updated data files
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/seen_products.json data/available_products.json
          git commit -m "Uppdatera data-filer efter monitor-körning" || echo "Inga ändringar att committa"
          git push
