name: Web Monitor

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:       # Möjliggör manuell körning från GitHub UI

permissions:
  contents: write          # Viktigt för att kunna pusha filer

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Ensure data folder and files exist
        run: |
          mkdir -p data
          # Skapa filer med giltig tom JSON "{}" om de inte finns
          if [ ! -s data/seen_products.json ]; then echo "{}" > data/seen_products.json; fi
          if [ ! -s data/available_products.json ]; then echo "{}" > data/available_products.json; fi

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run monitor script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit and push updated data files
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/seen_products.json data/available_products.json
          git commit -m "Uppdatera data-filer efter monitor-körning" || echo "Inga ändringar att committa"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Lorquette/web-monitor3.git
          git push origin HEAD:main
